name: Build Images

on:
  push:
    # tags:
    #  - '*'
    branches:
      - master

env:
  REGISTRY: ghcr.io
  

jobs:
  build-and-push-awms-hyperlogic-keycloak:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: rexchoppers
          password: ${{ secrets.GITHUB_TOKEN }}